Fixes @a[r=X]
oliverdunk/JukeboxAPI pull request #55
Opened 2021-06-10 08:27 UTC by GrangerTheDog

Fixes the error that happens when the Location and Player are not in the same world in the isInRange function!

Reported by 4P5#1749 in the Discord channel!
Caused by: java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether

2021-10-08 00:26 UTC, GrangerTheDog commented
Added some more stuff! Like the ability to use with 1.7-1.17

2021-12-22 00:07 UTC, TehBrian requested changes

2021-12-22 00:22 UTC, TehBrian commented on plugin/pom.xml
> +
unnecessary newlines

2021-12-22 00:22 UTC, TehBrian commented on plugin/src/main/java/net/mcjukebox/plugin/bukkit/MCJukebox.java
> +            throw new IllegalStateException("Tried to access Adventure when the plugin was disabled!");
nitpick, but the if statement style should match the rest of the project (space after `if`)

2021-12-22 00:22 UTC, TehBrian commented on plugin/src/main/java/net/mcjukebox/plugin/bukkit/utils/SpigotUtils.java
> +				.hoverEvent(HoverEvent.showText(LegacyComponentSerializer.legacy('&').deserialize(langManager.get("user.openClient")))).build();
`.legacy('&')` can be replaced with `.legacyAmpersand()`

2021-12-22 00:22 UTC, TehBrian commented on shared/pom.xml
> +
unnecessary newline addition

2024-10-06 20:19 UTC, closed without merging

2024-10-06 20:19 UTC, oliverdunk commented
Sorry for taking far too long with this one - I've extracted the bug fix into https://github.com/oliverdunk/JukeboxAPI/commit/b528fe305b084e4a31bf6026abc8924a1cbf0821. I'm going to close this since I think the rest of the changes are related to the volume work you've done which isn't currently supported by the public client.